# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ammount',
            new_name='amount',
        ),
    ]
